# Generated by Django 3.0.8 on 2020-07-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
